# Change this value to your own domain.
base_url = "zhan7318.github.io/Website/"

title = ""
description = ""

# minify_html = true
compile_sass = true

[extra]
author = "ACM UMN"
menu = [
    { url = "/", name = "Home" },
]
