# Change this value to your own domain.
base_url = "zhan7318.github.io/Website/"

title = ""
description = ""

# minify_html = true
compile_sass = true

[extra]
author = "raymond"
menu = [
    { url = "/", name = "Home" },
    { url = "https://bigrat.monster", name = "Bigrat" }
]
